---
- name: installing pacjkages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: installing httpd packages
    yum:
        name: httpd
        state: installed
    when: ansible_os_family == "RedHat"   
  - name: installing httpd packages on ubuntu
    apt:
        name: apache2
        state: present
    when: ansible_os_family == "Debian"

  - name: start httpd service on ubuntu
    service:
        name: apache2
        state: started
    when: ansible_os_family == "Debian"

  - name: ting httpd service
    service:
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"

  - name: copy index.html file
    copy:
            src: /home/ansadmin/playbooks/index.html
            dest: /var/www/html       
